// packages/components/src/.stories/components/Card.tsx
import type { JSX, Component, ComponentProps } from "solid-js"
import { splitProps } from "solid-js"

import { clsx } from 'clsx'

const Card: Component<ComponentProps<"div">> = (props) => {
  const [local, others] = splitProps(props, ["class"])
  return (
    <div
      class={clsx("rounded-lg border bg-card text-card-foreground shadow-sm", local.class)}
      {...others}
    />
  )
}

const CardHeader: Component<ComponentProps<"div"> & {
  title?: JSX.Element;
  description?: JSX.Element;
}> = (props) => {
  const [local, others] = splitProps(props, ["class", "children", "title", "description"])
  return (
    <div
      class={clsx("flex flex-col space-y-1.5 p-6", local.class)}
      {...others}
    >
      {local.title && (
        <CardTitle>
          {local.title}
        </CardTitle>
      )}
      {local.description && (
        <CardDescription>
          {local.description}
        </CardDescription>
      )}
      {local.children}
    </div>
  )
}

const CardTitle: Component<ComponentProps<"h3">> = (props) => {
  const [local, others] = splitProps(props, ["class"])
  return (
    <h3 class={clsx("text-lg font-semibold leading-none tracking-tight", local.class)} {...others} />
  )
}

const CardDescription: Component<ComponentProps<"p">> = (props) => {
  const [local, others] = splitProps(props, ["class"])
  return <p class={clsx("text-sm text-muted-foreground", local.class)} {...others} />
}

const CardContent: Component<ComponentProps<"div">> = (props) => {
  const [local, others] = splitProps(props, ["class"])
  return <div class={clsx("p-6 pt-0", local.class)} {...others} />
}

const CardFooter: Component<ComponentProps<"div">> = (props) => {
  const [local, others] = splitProps(props, ["class"])
  return <div class={clsx("flex items-center p-6 pt-0", local.class)} {...others} />
}

export { Card, CardHeader, CardFooter, CardTitle, CardDescription, CardContent }

// packages/inspector/src/.stories/components/Card.tsx
/**
 * https://ui.shadcn.com/docs/components/card
 */

import {
  forwardRef,
  type ReactNode,
  type HTMLAttributes,
} from 'react'

import cn from 'clsx'

export const Card = forwardRef<
  HTMLDivElement,
  HTMLAttributes<HTMLDivElement>
>(({ className, ...props }, ref) => (
  <div
    ref={ref}
    className={cn(
      'rounded-lg border bg-card text-card-foreground shadow-sm',
      className,
    )}
    {...props}
  />
))
Card.displayName = 'Card'

export const CardHeader = forwardRef<
  HTMLDivElement,
  HTMLAttributes<HTMLDivElement> & {
    title?: ReactNode;
    description?: ReactNode;
  }
>(({
  className, title, description, children, ...props
}, ref) => (
  <div
    ref={ref}
    className={cn('flex flex-col space-y-2.5 p-6', className)}
    {...props}
  >
    {title && (
      <CardTitle>
        {title}
      </CardTitle>
    )}
    {description && (
      <CardDescription>
        {description}
      </CardDescription>
    )}
    {children}
  </div>
))
CardHeader.displayName = 'CardHeader'

export const CardTitle = forwardRef<
  HTMLParagraphElement,
  HTMLAttributes<HTMLHeadingElement>
>(({ className, ...props }, ref) => (
  <h3
    ref={ref}
    className={cn(
      'text-2xl font-semibold leading-none tracking-tight',
      className,
    )}
    {...props}
  />
))
CardTitle.displayName = 'CardTitle'

export const CardDescription = forwardRef<
  HTMLParagraphElement,
  HTMLAttributes<HTMLParagraphElement>
>(({ className, ...props }, ref) => (
  <p
    ref={ref}
    className={cn('text-sm text-muted-foreground', className)}
    {...props}
  />
))
CardDescription.displayName = 'CardDescription'

export const CardContent = forwardRef<
  HTMLDivElement,
  HTMLAttributes<HTMLDivElement>
>(({ className, ...props }, ref) => (
  <div ref={ref} className={cn('p-6 pt-0', className)} {...props} />
))
CardContent.displayName = 'CardContent'

export const CardFooter = forwardRef<
  HTMLDivElement,
  HTMLAttributes<HTMLDivElement>
>(({ className, ...props }, ref) => (
  <div
    ref={ref}
    className={cn(' flex items-center p-6 pt-0', className)}
    {...props}
  />
))
CardFooter.displayName = 'CardFooter'
